version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pixegotchi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpixe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pixegotchi-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pixegotchi-network

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    # image: fediukv/pixegotchi-backend:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:adminpixe@postgres:5432/pixegotchi?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      TELEGRAM_BOT_TOKEN: your-bot-token
      REDIS_URL: redis://redis:6379
      TON_NETWORK: testnet
      NODE_ENV: development
    env_file:
      - ./packages/backend/.env
    volumes:
      - ./packages/backend/src:/app/src
      - ./packages/backend/prisma:/app/prisma
      - ./packages/backend/.env:/app/.env
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - pixegotchi-network
    command: sh -c "sleep infinity"
    # command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run dev"

  prisma-studio:
    build:
      context: ./packages/backend
      dockerfile: prisma-studio.Dockerfile
    command: sh -c "sleep infinity"
    # command: sh -c "npx prisma studio --port 51212 --hostname 0.0.0.0"
    ports:
      - "51212:51212"
    environment:
      - DATABASE_URL=postgresql://admin:adminpixe@postgres:5432/pixegotchi?schema=public
    depends_on:
      - postgres
    networks:
      - pixegotchi-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  pixegotchi-network:
    driver: bridge
