version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pixegotchi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpixe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pixegotchi-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pixegotchi-network
    restart: unless-stopped

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    # image: fediukv/pixegotchi-backend:latest
    ports:
      - "3000:3000"
    # expose:
    #   - "3000"
    environment:
      DATABASE_URL: postgresql://admin:adminpixe@postgres:5432/pixegotchi?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      TELEGRAM_BOT_TOKEN: your-bot-token
      REDIS_URL: redis://redis:6379
      TON_NETWORK: testnet
      NODE_ENV: development
    env_file:
      - ./packages/backend/.env
    volumes:
      - ./packages/backend/src:/app/src
      - ./packages/shared:/shared
      - ./packages/backend/prisma:/app/prisma
      - ./packages/backend/.env:/app/.env
    depends_on:
      - postgres
      - redis
    networks:
      - pixegotchi-network
    # command: sh -c 'sleep infinity'
    # command: sh -c "npm run dev:docker"
    # command: sh -c "npm install && npm run dev"
    command: sh -c "npm run prisma:generate && npm run prisma:migrate && npm run dev"
    restart: unless-stopped

  prisma-studio:
    build:
      context: ./packages/backend
      dockerfile: prisma-studio.Dockerfile
    # image: fediukv/pixegotchi-prisma-studio:latest
    ports:
      - "51212:51212"
    # expose:
    #   - "51212"
    environment:
      - DATABASE_URL=postgresql://admin:adminpixe@postgres:5432/pixegotchi?schema=public
    volumes:
      - ./packages/backend/prisma:/app/prisma
      - ./packages/backend/.env:/app/.env
    depends_on:
      - postgres
    networks:
      - pixegotchi-network
    command: sh -c "npx prisma generate && BROWSER=none npx prisma studio --port 51212"
    restart: unless-stopped

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./packages/nginx/conf.d:/etc/nginx/conf.d
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #     - ./packages/nginx/.htpasswd:/etc/nginx/.htpasswd
  #   depends_on:
  #     - backend
  #     - prisma-studio
  #   networks:
  #     - pixegotchi-network
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  pixegotchi-network:
    driver: bridge
