import type { Prisma } from "../generated/prisma/client";
import { pathToFileURL } from "node:url";
import { prisma } from "@/database/prisma";

export const DEFAULT_ROOM_COSMETICS = [
  {
    id: "violet-brick",
    name: "Violet brick",
    slot: "environment",
    rarity: "common",
    assetUrl: null,
    environmentId: null,
    allowedPositions: [],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "midnight-brick",
    name: "Midnight brick",
    slot: "environment",
    rarity: "common",
    assetUrl: null,
    environmentId: null,
    allowedPositions: [],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "warm-plaster",
    name: "Warm plaster",
    slot: "environment",
    rarity: "common",
    assetUrl: null,
    environmentId: null,
    allowedPositions: [],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "plum-boards",
    name: "Plum boards",
    slot: "floor",
    rarity: "common",
    assetUrl: null,
    environmentId: null,
    allowedPositions: [],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "dark-boards",
    name: "Dark boards",
    slot: "floor",
    rarity: "common",
    assetUrl: null,
    environmentId: null,
    allowedPositions: [],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "honey-boards",
    name: "Honey boards",
    slot: "floor",
    rarity: "common",
    assetUrl: null,
    environmentId: null,
    allowedPositions: [],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "arched-window-day",
    name: "Window",
    slot: "window",
    rarity: "common",
    assetUrl: "assets/room/windows/arched-window-day.png",
    environmentId: null,
    allowedPositions: [6],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "pink-window-curtains",
    name: "Pink curtains",
    slot: "curtain",
    rarity: "common",
    assetUrl: "assets/room/curtains/pink-window-curtains.png",
    environmentId: null,
    allowedPositions: [7],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "tall-cabinet-wood",
    name: "Cabinet",
    slot: "furniture",
    rarity: "common",
    assetUrl: "assets/room/furniture/tall-cabinet-wood.png",
    environmentId: null,
    allowedPositions: [1, 3],
    span: 2,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "purple-sofa",
    name: "Purple sofa",
    slot: "sofa",
    rarity: "common",
    assetUrl: "assets/room/furniture/purple-sofa.png",
    environmentId: null,
    allowedPositions: [8],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "blue-sofa",
    name: "Blue sofa",
    slot: "sofa",
    rarity: "common",
    assetUrl: "assets/room/furniture/blue-sofa.png",
    environmentId: null,
    allowedPositions: [8],
    span: 1,
    allowOverlap: false,
    isDefault: false,
    isLimited: false,
    isTradable: true,
    isPurchasable: true,
    pgcPrice: 400,
    isActive: true,
  },
  {
    id: "purple-oval-rug",
    name: "Purple rug",
    slot: "rug",
    rarity: "common",
    assetUrl: "assets/room/rugs/purple-oval-rug.png",
    environmentId: null,
    allowedPositions: [9],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "blue-oval-rug",
    name: "Blue rug",
    slot: "rug",
    rarity: "common",
    assetUrl: "assets/room/rugs/blue-oval-rug.png",
    environmentId: null,
    allowedPositions: [9],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "botanical-frame",
    name: "Wall art",
    slot: "wallArt",
    rarity: "common",
    assetUrl: "assets/room/wall-art/botanical-frame.png",
    environmentId: null,
    allowedPositions: [1, 3],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "yellow-lantern",
    name: "Lantern",
    slot: "decor",
    rarity: "common",
    assetUrl: "assets/room/decor/yellow-lantern.png",
    environmentId: null,
    allowedPositions: [10, 11],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
  {
    id: "bonsai-pot",
    name: "Bonsai",
    slot: "decor",
    rarity: "common",
    assetUrl: "assets/room/decor/bonsai-pot.png",
    environmentId: null,
    allowedPositions: [10, 11],
    span: 1,
    allowOverlap: false,
    isDefault: true,
    isLimited: false,
    isTradable: false,
    isPurchasable: false,
    pgcPrice: null,
    isActive: true,
  },
] satisfies Prisma.CosmeticAssetCreateManyInput[];

export async function seedRoomCosmetics() {
  await prisma.$transaction(
    DEFAULT_ROOM_COSMETICS.map(({ id, ...asset }) =>
      prisma.cosmeticAsset.upsert({
        where: { id },
        create: { id, ...asset },
        update: asset,
      }),
    ),
  );
}

async function main() {
  console.log("Seeding Room Cosmetics catalog...");
  await seedRoomCosmetics();
  console.log(`Seeded ${DEFAULT_ROOM_COSMETICS.length} Room Cosmetics assets.`);
}

const isDirectExecution =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (isDirectExecution) {
  main()
    .catch((error) => {
      console.error("Room Cosmetics seed failed:", error);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
