import { ChestType, ItemType } from "../../enums";

export const ITEMS_IMG: Record<ItemType, Record<string | ChestType, string>> = {
  food: {
    apple: "🍎",
    peach: "🍑",
    chicken: "🍗",
    bakon: "🥓",
    burger: "🍔",
    lobster: "🦞",
  },
  cleaning: {
    water: "💦",
    tooth_brush: "🪥",
    sponche: "🧽",
    soap: "🧼",
    shower: "🚿",
    bath: "🛁",
  },
  medicine: {
    thermometer: "🌡",
    bandage: "🩹",
    pill: "💊",
    small_medicine: "💉",
    cure: "🧪",
    antidote: "⚗️",
  },
  toy: {
    small_toy: "🪀",
    rubber_ball: "☄️",
    puzzle: "🧩",
    plush: "🧸",
    magic_wand: "🪄",
    gamepad: "🎮",
  },
  boost: {
    coffee: "☕️",
    energy_drink: "🧋",
    power_bar: "🍫",
    lightning_flask: "⚡️",
    divine_spark: "🌩",
    mega_boost: "🚀",
  },
  special: {
    rename_tag: "🏷",
    lucky_charm: "🍀",
    exp_booster: "📈",
    double_xp: "🌟",
    revive_stone: "💎",
    wish_scroll: "📜",
  },
  chest: {
    wooden: "🪵",
    silver: "🪙",
    golden: "⚜️",
    crystal: "🔮",
    mythic: "🎁",
    legendary: "💠",
  },
};
