import path from "node:path";
import { compiledIndexPath, readText, summarizeMarkdown, toVaultLink, vaultRoot, walkMarkdownFiles, writeText } from "./common.mjs";

const pages = await walkMarkdownFiles(vaultRoot);
const grouped = new Map();

for (const filePath of pages) {
  const relative = path.relative(vaultRoot, filePath).split(path.sep).join("/");
  if (relative.startsWith(".obsidian/")) {
    continue;
  }

  const folder = relative.split("/")[0] ?? "Vault";
  const content = await readText(filePath);
  const title = content.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? path.basename(filePath, ".md");
  const summary = summarizeMarkdown(content);
  const item = { filePath, title, summary };

  if (!grouped.has(folder)) {
    grouped.set(folder, []);
  }

  grouped.get(folder).push(item);
}

const folderOrder = Array.from(grouped.keys()).sort((left, right) => left.localeCompare(right));
const lines = [];

lines.push("# Vault Index");
lines.push("");
lines.push("Generated by `npm run wiki:compile`.");
lines.push("");
lines.push("## Sections");
lines.push("");

for (const folder of folderOrder) {
  lines.push(`### ${folder}`);
  lines.push("");

  const items = grouped.get(folder).sort((left, right) => left.title.localeCompare(right.title));
  for (const item of items) {
    const link = toVaultLink(item.filePath);
    const summary = item.summary ? ` - ${item.summary}` : "";
    lines.push(`- ${link} ${summary}`.trimEnd());
  }

  lines.push("");
}

lines.push("## Notes");
lines.push("");
lines.push("- `Home` is the human-friendly entry point.");
lines.push("- `Log` is append-only.");
lines.push("- `Index` is regenerated from the current vault contents.");
lines.push("");

await writeText(compiledIndexPath, `${lines.join("\n")}\n`);

console.log(`Wrote ${path.relative(process.cwd(), compiledIndexPath)}`);
