import { Pixegotchi } from "./mainPageTypes";
export const pixe: Pixegotchi = {
  id: 1,
  userId: 1,
  nftAddress: null,
  genomeHash: "genome",
  element: "air",
  rarity: "rare",
  gender: "male",
  name: "Uni",
  status: "active",
  level: 1,
  experience: 356,
  health: 85,
  hunger: 85,
  energy: 85,
  happiness: 85,
  cleanliness: 85,
  criticalSince: null,
  lastFedAt: null,
  lastPlayedAt: null,
  lastSleptAt: null,
  lastCleanedAt: null,
  lastHealedAt: null,
  lastUpdateAt: null,
  createdAt: null,
};
