import {
  Pixegotchi,
  ElementType,
  RarityType,
  PixegotchiStatus,
  PixegotchiGender,
} from "@shared";
export const pixe: Pixegotchi = {
  id: 1,
  userId: 1,
  nftAddress: null,
  genomeHash: "genome",
  element: "fire" as ElementType,
  rarity: "rare" as RarityType,
  gender: "male" as PixegotchiGender,
  name: "Uni",
  status: "active" as PixegotchiStatus,
  level: 1,
  experience: 356,
  health: 85,
  hunger: 85,
  energy: 85,
  happiness: 85,
  cleanliness: 85,
  criticalSince: null,
  lastFedAt: null,
  lastPlayedAt: null,
  lastSleptAt: null,
  lastCleanedAt: null,
  lastHealedAt: null,
  lastUpdateAt: null,
  createdAt: null,
  traits: [],
};
